### ISSUE TITLE
TNC fare and wait time not applied to TNC transit trips

### ISSUE THREAD

**Issue by aber-sandag** [SANDAG/ABM#122]
https://github.com/SANDAG/ABM/blob/ABM3_develop/src/asim/configs/resident/trip_mode_choice.csv#L282

TNC transit trips only have transit fare applied, TNC fare is missing. 

Additionally, microtransit access should not calculate transit fare differently than TNC access. TNC and KNR access skims should be the same. Conversion from dollars to cents is also missing with microtransit access.

**Comment by JoeJimFlood** [comment]
The use of the KnR skims for microtransit access was intentional. The model assumes that the microtransit/NEV fare is free when accessing/egressing from fixed route transit. This is how [Beach Bug](https://www.sandag.org/projects-and-programs/innovative-mobility/flexible-fleets/pacific-beach-shuttle#:~:text=How%20much%20does%20a%20ride,group%20of%20two%20or%20more.) operates, and I had confirmed with planners that we could assume that all services will operate that way. I figured that the trip effectively became a KnR trip, so I used that skim.

As for the conversion of fare from dollars to cents, the [microtransit](https://github.com/SANDAG/ABM/blob/ABM3_develop/src/asim/configs/common/constants.yaml#L277) and [NEV](https://github.com/SANDAG/ABM/blob/ABM3_develop/src/asim/configs/common/constants.yaml#L283) fares are already stored in cents in the constants file.

**Comment by aber-sandag** [comment]
@JoeJimFlood I believe the TNC access skims do not include TNC fare, only the transit fare. As such there is no reason to use KNR skims over TNC skims, both should return the same value. We need to add TNC fare separately.

The missing conversion from dollars to cents here is on the transit fare, not the microtransit/NEV fare.

**Comment by aber-sandag** [comment]
Wait time is also not added for TNC access/egress. Wait time is currently added for microtransit/nev access/egress however.

**Comment by aber-sandag** [comment]
Resolved by https://github.com/SANDAG/ABM/commit/f9fef4f58646f2050c5211e5f8a6824587ecf471
