### ISSUE TITLE
Parking location choice not choosing parking zones

### ISSUE THREAD

**Issue by JoeJimFlood** [SANDAG/ABM#69]
The result is that the parking_zone is -1 for all trips

**Comment by dhensle** [comment]
Fixed with https://github.com/SANDAG/ABM/commit/1d95d2f566e2b9e97fd6a6e3bc2d3cb8f7acc580.  The parking location choice model was running with 0 choosers. This had to do with a setting not actually existing.  If you replace setting('segment') with "no_segmentation" in the preprocessor to match the column name in the parking_location_choice.csv, it makes it such that all trips are treated in the same segment.
